services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "3010:3010"
    volumes:
      - .:/app
    command: pnpm start
  mongo:
    image: mongo:8.0.3
    container_name: sf-db
    ports:
      - "27017:27017"
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

networks:
  backend:
    name: backend