services:
  backend:
    image: ghcr.io/maelstromeous/satisfactory-factories:backend-latest
    container_name: sf-backend
    pull_policy: missing  # Ensures that the latest image is always pulled
    networks:
      - backend
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://sf-db:27017/factory_planner
    ports:
      - "4000:3010"
    command: pnpm start
  mongo:
    image: mongo:8.0.3
    container_name: sf-db
    ports:
      - "27117:27017"
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

networks:
  backend:
    name: sf-backend