import type { Factory, FactoryTab } from '../types/factory'
import { ItemType } from '../types/factory'

/** A minimal factory that satisfies every required field of the schema. */
export const makeFactory = (overrides: Partial<Factory> = {}): Factory => ({
  id: 1,
  name: 'Iron Works',
  inputs: [],
  previousInputs: [],
  products: [{
    id: 'IronIngot',
    recipe: 'IngotIron',
    amount: 30,
    displayOrder: 0,
    requirements: { OreIron: { amount: 30 } },
    buildingRequirements: { name: 'smeltermk1', amount: 1 },
    buildingGroups: [{
      id: 0,
      buildingCount: 1,
      overclockPercent: 100,
      parts: { OreIron: 30 },
      powerUsage: 4,
      powerProduced: 0,
      type: ItemType.Product,
    }],
    buildingGroupsTrayOpen: false,
    buildingGroupsHaveProblem: false,
    buildingGroupItemSync: true,
    completed: true,
    checklistSyncedAmount: 30,
  }],
  byProducts: [],
  powerProducers: [],
  customBuildings: [{
    id: 'cb-1',
    building: 'portal',
    amount: 1,
    ingredients: [{ part: 'SingularityCell', perMin: 10 }],
    powerConsumed: 500,
    displayOrder: 0,
  }],
  parts: {
    IronIngot: {
      amountRequired: 0,
      amountRequiredProduction: 0,
      amountRequiredExports: 0,
      amountRequiredPower: 0,
      amountSupplied: 30,
      amountSuppliedViaInput: 0,
      amountSuppliedViaRaw: 0,
      amountSuppliedViaProduction: 30,
      amountRemaining: -30,
      isRaw: false,
      amountRequiredBuildings: 0,
      isEndProduct: false,
      isSinkable: true,
      amountRequiredSink: 30,
      amountRemainingPreSink: -30,
      satisfied: true,
      exportable: true,
    },
  },
  buildingRequirements: { smeltermk1: { name: 'smeltermk1', amount: 1 } },
  buildingMaterialCosts: {},
  requirementsSatisfied: true,
  exportCalculator: {
    IronIngot: { selected: null, factorySettings: {} },
  },
  partDisposal: { IronIngot: { sinks: 2, depots: 1 } },
  dependencies: { requests: {}, metrics: {} },
  rawResources: {},
  power: { consumed: 4, produced: 0, difference: -4 },
  usingRawResourcesOnly: false,
  hidden: false,
  hasProblem: false,
  inSync: null,
  syncState: {},
  syncStatePower: {},
  syncStateCustomBuildings: { 'cb-1': { building: 'portal', amount: 1, ingredientAmount: 10 } },
  displayOrder: 0,
  tasks: [],
  notes: '',
  checklistEnabled: true,
  checklistPanelHidden: false,
  checklistExports: { '2:IronIngot': true },
  checklistExportSyncedAmounts: { '2:IronIngot': 30 },
  dataVersion: '1.2-05',
  ...overrides,
})

export const makeFactoryTab = (overrides: Partial<FactoryTab> = {}): FactoryTab => ({
  id: 'd0a2b0e2-0000-4000-8000-000000000000',
  name: 'My Plan',
  factories: [makeFactory()],
  depotUploadTier: 2,
  depotExpansionTier: 1,
  plannerVersion: '0.6.0',
  ...overrides,
})
