<!-- The heading above a group's cards in the planner. Deliberately lighter than the sidebar's
     header: the sidebar is where you manage groups, this is a signpost while scrolling. -->
<template>
  <div :id="bandId" class="group-band" :class="{ ungrouped: !group }" :style="colorVars">
    <div class="d-flex align-center ga-2 px-3 py-2">
      <!-- Two keyed icons rather than one with a bound class: Font Awesome swaps the <i> for an
           <svg> Vue no longer owns, so a class flip leaves the chevron pointing the same way. -->
      <v-btn
        class="chevron"
        density="compact"
        icon
        size="small"
        :title="collapsed ? 'Expand group' : 'Collapse group'"
        variant="text"
        @click="$emit('toggle')"
      >
        <span v-if="collapsed" key="shut"><i class="fas fa-chevron-right" /></span>
        <span v-else key="open"><i class="fas fa-chevron-down" /></span>
      </v-btn>
      <span class="band-title text-h6">{{ group?.name ?? 'Ungrouped' }}</span>
      <v-chip class="sf-chip small no-margin factory" variant="tonal">
        <i class="fas fa-industry" />
        <span class="ml-2">{{ count }}</span>
      </v-chip>

      <!-- What the group costs and makes, so a band is worth reading rather than just dividing. -->
      <tooltip :text="`Power generated by this group: ${formatMw(power.produced)}`">
        <v-chip class="sf-chip small no-margin generation" variant="tonal">
          <i class="fas fa-bolt mr-1" /><i class="fas fa-plus" />
          <span class="ml-2">{{ formatMw(power.produced) }}</span>
        </v-chip>
      </tooltip>
      <tooltip :text="`Power consumed by this group: ${formatMw(power.consumed)}`">
        <v-chip class="sf-chip small no-margin consumption" variant="tonal">
          <i class="fas fa-bolt mr-1" /><i class="fas fa-minus" />
          <span class="ml-2">{{ formatMw(power.consumed) }}</span>
        </v-chip>
      </tooltip>
      <tooltip :text="`This group ${power.difference < 0 ? 'draws' : 'has a surplus of'} ${formatMw(Math.abs(power.difference))}`">
        <v-chip
          class="sf-chip small no-margin"
          :class="power.difference < 0 ? 'error' : 'success'"
          variant="tonal"
        >
          <i class="fas fa-balance-scale" />
          <span class="ml-2">{{ formatMw(power.difference) }}</span>
        </v-chip>
      </tooltip>
      <tooltip v-if="problems" :text="`${problems} ${problems === 1 ? 'factory' : 'factories'} in this group needs attention`">
        <v-chip class="sf-chip small error no-margin" variant="tonal">
          <i class="fas fa-exclamation-triangle" />
          <span class="ml-2">{{ problems }}</span>
        </v-chip>
      </tooltip>

      <v-spacer />
      <span v-if="collapsed" class="text-body-2 text-medium-emphasis">
        {{ count }} {{ count === 1 ? 'factory' : 'factories' }} hidden
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { computed } from 'vue'
  import { Factory, FactoryGroup } from '@/interfaces/planner/FactoryInterface'
  import { groupColorVars } from '@/utils/colors'
  import { calculateTotalPower } from '@/utils/statistics'
  import { formatMw } from '@/utils/numberFormatter'
  import { hasFactoryProblem } from '@/utils/factory-management/status'

  const props = defineProps<{
    group: FactoryGroup | null
    count: number
    collapsed: boolean
    factories: Factory[]
  }>()

  // The band is the only summary a collapsed group has, so it carries the group's own power
  // balance rather than making you open it to find out what it costs.
  const power = computed(() => {
    const totals = calculateTotalPower(props.factories)
    return {
      produced: totals.totalPowerProduced,
      consumed: totals.totalPowerConsumed,
      difference: totals.totalPowerDifference,
    }
  })

  const problems = computed(() => props.factories.filter(hasFactoryProblem).length)

  defineEmits<{ (event: 'toggle'): void }>()

  // Element id so the scroll-spy can see the band and the sidebar can jump to it.
  const bandId = computed(() => `group-${props.group?.id ?? 'ungrouped'}`)

  const colorVars = computed(() => (props.group ? groupColorVars(props.group.color) : {}))
</script>

<style lang="scss" scoped>
// Must match Planner.vue's $tree-line: the band's left edge is the top of the same line the cards
// hang off, and a 2px band over a 3px trunk steps visibly where the two meet.
$tree-line: 3px;

.group-band {
  position: relative;
  border-radius: 4px;
  margin-bottom: 8px;
  background-color: var(--sf-group-muted, rgba(255, 255, 255, 0.05));
  border: 2px solid var(--sf-group, #6c6c6c);
}

// The band is the head of the tree, so its left edge is drawn as the trunk rather than as a
// border that happens to be the same colour: full trunk width, and squared off at the bottom so
// the line carries straight on into the cards instead of curving away from them.
.group-band:not(.ungrouped) {
  border-left-width: $tree-line;
  border-bottom-left-radius: 0;
  // The gap to the first card is that card's padding, not this band's margin. A margin sits
  // outside both boxes, so nothing draws in it and the trunk arrives with a hole above it —
  // and bridging it from this side lands short, because `bottom` on an absolutely positioned
  // child resolves against the padding box and the bottom border swallows the last of it. As the
  // card's padding it is simply inside the trunk. See Planner.vue's $band-gap.
  margin-bottom: 0;
}

// The top of the trunk the cards hang off, bridging the band's own 8px bottom margin so the line
// runs unbroken from the band's edge into the first card. Ungrouped draws no tree and so no stub —
// see Planner.vue for the rest of the geometry.
.chevron {
  font-size: 1.1rem;
}

.band-title {
  font-weight: 500;
}

.ungrouped .band-title {
  color: #bdbdbd;
  font-style: italic;
}
</style>
