<!-- The heading above a grouped factory in the planner. Deliberately lighter than the sidebar's
     header: the sidebar is where you manage groups, this says which group the factory on screen
     belongs to, where in it you are, and how the group as a whole is doing. -->
<template>
  <div :id="bandId" class="group-band" data-testid="group-band" :style="colorVars">
    <div class="d-flex align-center ga-2 px-3 py-2">
      <!-- The same swatch the sidebar header carries, and it does the same thing: the band is
           where you are looking when a group's colour turns out to be wrong. -->
      <factory-group-color-menu
        :model-value="group.color"
        @update:model-value="setGroupColor(group.id, $event)"
      />
      <span class="band-title text-h6">{{ group.name }}</span>
      <!-- What the group is, next to its name: where the factory on screen sits in it, and how
           many of its factories are in trouble. The power figures are what it costs, which belongs
           with the totals on the right rather than in the middle of the title. -->
      <tooltip :text="`Factory ${position} of ${factories.length} in this group`">
        <v-chip class="sf-chip small no-margin factory" data-testid="group-band-position" variant="tonal">
          <i class="fas fa-industry" />
          <span class="ml-2">{{ position }} / {{ factories.length }}</span>
        </v-chip>
      </tooltip>
      <!-- The same chips, icons and colours the Factories Summary and the sidebar use, so one
           tier of trouble looks the same wherever it is counted. -->
      <tooltip
        v-for="chip in statusTally"
        :key="chip.key"
        :text="chip.tooltip"
      >
        <v-chip class="sf-chip small no-margin" :class="chip.class" variant="tonal">
          <i :class="chip.icon" />
          <span class="ml-2">{{ chip.count }}</span>
        </v-chip>
      </tooltip>

      <v-spacer />

      <tooltip :text="`Power generated by this group: ${formatMw(power.produced)}`">
        <v-chip class="sf-chip small no-margin generation" variant="tonal">
          <i class="fas fa-bolt mr-1" /><i class="fas fa-plus" />
          <span class="ml-2">{{ formatMw(power.produced) }}</span>
        </v-chip>
      </tooltip>
      <tooltip :text="`Power consumed by this group: ${formatMw(power.consumed)}`">
        <v-chip class="sf-chip small no-margin consumption" variant="tonal">
          <i class="fas fa-bolt mr-1" /><i class="fas fa-minus" />
          <span class="ml-2">{{ formatMw(power.consumed) }}</span>
        </v-chip>
      </tooltip>
      <!-- Augmenters in this group boost the whole plan's generation, not this group's, so the
           figure is called out rather than folded into the group's own total. -->
      <tooltip
        v-if="power.boost > 0"
        :text="`Alien Power Augmenters in this group add ${formatMw(power.boost)} to the grid, a percentage of the plan's total generation, counted in the plan's power rather than this group's.`"
      >
        <v-chip class="sf-chip small no-margin circuit-boost" variant="tonal">
          <i class="fas fa-bolt" /><i class="fas fa-arrow-up" />
          <span class="ml-2">{{ formatMw(power.boost) }}</span>
        </v-chip>
      </tooltip>
      <tooltip :text="`This group ${power.difference < 0 ? 'draws' : 'has a surplus of'} ${formatMw(Math.abs(power.difference))}`">
        <v-chip
          class="sf-chip small no-margin"
          :class="power.difference < 0 ? 'error' : 'success'"
          variant="tonal"
        >
          <i class="fas fa-balance-scale" />
          <span class="ml-2">{{ formatMw(power.difference) }}</span>
        </v-chip>
      </tooltip>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { computed } from 'vue'
  import { Factory, FactoryGroup } from '@/interfaces/planner/FactoryInterface'
  import { groupColorVars } from '@/utils/colors'
  import { calculateTotalPower } from '@/utils/statistics'
  import { formatMw } from '@/utils/numberFormatter'
  import {
    factoryStatusTallyChips,
    getFactoryStatuses,
    tallyFactoryStatuses,
  } from '@/utils/factory-management/status'
  import { useFactoryGroups } from '@/composables/useFactoryGroups'

  const props = defineProps<{
    group: FactoryGroup
    // 1-based place of the factory on screen among the group's factories.
    position: number
    factories: Factory[]
  }>()

  // Only one of the group's factories is on screen, so the band carries the group's own power
  // balance rather than making you visit each member to find out what it costs.
  const power = computed(() => {
    const totals = calculateTotalPower(props.factories)
    return {
      produced: totals.totalPowerProduced,
      consumed: totals.totalPowerConsumed,
      difference: totals.totalPowerDifference,
      boost: totals.totalPowerBoost,
    }
  })

  // Counted the same way the Factories Summary counts the plan, from the same helper.
  const statusTally = computed(() => factoryStatusTallyChips(
    tallyFactoryStatuses(props.factories.map(factory => getFactoryStatuses(factory)))
  ))

  const { setGroupColor } = useFactoryGroups()

  const bandId = computed(() => `group-${props.group.id}`)

  const colorVars = computed(() => groupColorVars(props.group.color))
</script>

<style lang="scss" scoped>
.group-band {
  position: relative;
  border-radius: 4px;
  margin-bottom: 8px;
  background-color: var(--sf-group-muted, rgba(255, 255, 255, 0.05));
  border: 2px solid var(--sf-group, #6c6c6c);
  border-left-width: 6px;
}

.band-title {
  font-weight: 500;
}
</style>
