/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/changelog': RouteRecordInfo<
      '/changelog',
      '/changelog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error': RouteRecordInfo<
      '/error',
      '/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/graph': RouteRecordInfo<
      '/graph',
      '/graph',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/parts': RouteRecordInfo<
      '/parts',
      '/parts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/recipes': RouteRecordInfo<
      '/recipes',
      '/recipes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/share/[id]': RouteRecordInfo<
      '/share/[id]',
      '/share/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/changelog.vue': {
      routes:
        | '/changelog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error.vue': {
      routes:
        | '/error'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/graph.vue': {
      routes:
        | '/graph'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/parts.vue': {
      routes:
        | '/parts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/recipes.vue': {
      routes:
        | '/recipes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/share/[id].vue': {
      routes:
        | '/share/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
