/**
 * Loading the committed .sav fixtures.
 *
 * These are real saves generated by the game, not fabricated bytes. That matters: the format
 * assumptions in this folder are only worth anything if they are checked against files the game
 * actually wrote, and a hand-built fixture would agree with whatever the parser happens to do.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { SaveBytes } from '@/utils/game-save/chunks'

export const SAVE_FIXTURE_DIR = join(__dirname, '../../../testing/fixtures/saves')

export type SaveFixture =
  | 'vanilla' |
  'vanilla-all-pure' |
  'fossil-fuel-rich' |
  'advanced-rich' |
  'node-randomised'

export const loadSaveFixture = (name: SaveFixture): SaveBytes =>
  new Uint8Array(readFileSync(join(SAVE_FIXTURE_DIR, `${name}.sav`)))
