<template>
  <v-toolbar dark :density="toolbarDensity">
    <v-btn v-if="mdAndDown" icon @click="toggleDrawer">
      <i class="fa fa-bars" />
    </v-btn>
    <template v-else>
      <img alt="Site logo" src="/assets/img/SF.png" style="max-width: 48px;">
      <h1 class="ml-3 font-weight-bold text-h6">Satisfactory Factories</h1>
      <span class="ml-2">
        <v-chip class="sf-chip blue small">
          BETA v0.5
          <span class="mx-1">•</span>
          <a class="show-changes" href="#" @click.prevent="showChanges">Show changes</a>
        </v-chip>
      </span>
    </template>
    <v-tabs
      v-model="currentTab"
    >
      <v-tab
        v-for="tab in tabItems"
        :key="tab.title"
        :prepend-icon="tab.icon"
        :text="tab.title"
        :to="tab.href"
        :value="tab.href"
      />
    </v-tabs>

    <template v-if="!mdAndDown">
      <ko-fi />
      <join-discord text="Discord" />
    </template>
    <template v-if="!mdAndDown" #append>
      <slot name="append" />
    </template>
  </v-toolbar>

  <v-navigation-drawer
    v-model="isDrawerOpen"
    class="pa-2"
    :class="{ resizing: isResizingDrawer }"
    :width="drawerWidth"
  >
    <div id="navigationDrawer" /> <!-- Generated by Planner.vue -->
    <div
      class="drawer-resize-handle"
      :class="{ resizing: isResizingDrawer }"
      @mousedown.prevent="startDrawerResize"
    />
    <template #append>
      <div class="d-flex flex-column ga-2">
        <v-divider color="#ccc" thickness="2px" />
        <slot name="append" />
        <div class="d-flex justify-center">
          <ko-fi />
        </div>
        <join-discord text="Discord" />
      </div>
    </template>
  </v-navigation-drawer>
</template>

<script setup lang="ts">
  import { useDisplay } from 'vuetify'
  import eventBus from '@/utils/eventBus'
  const { mdAndDown } = useDisplay()

  const toolbarDensity = computed(() => mdAndDown.value ? 'compact' : undefined)
  const isDrawerOpen = ref(false)
  const currentTab = ref(null)

  const toggleDrawer = () => {
    isDrawerOpen.value = !isDrawerOpen.value
  }

  // The tray can be dragged wider (never narrower than its default, capped at
  // 75% of the viewport) — same interaction as the docked sidebar in Planner.vue.
  const minDrawerWidth = 375
  const drawerWidth = ref<number>(parseInt(localStorage.getItem('drawerWidth') ?? '', 10) || minDrawerWidth)
  const isResizingDrawer = ref(false)

  const startDrawerResize = (event: MouseEvent) => {
    isResizingDrawer.value = true
    const startX = event.clientX
    const startWidth = drawerWidth.value

    // Lock the cursor and text selection for the duration of the drag
    document.body.style.cursor = 'col-resize'
    document.body.style.userSelect = 'none'

    const onMouseMove = (moveEvent: MouseEvent) => {
      const newWidth = startWidth + (moveEvent.clientX - startX)
      drawerWidth.value = Math.min(Math.max(newWidth, minDrawerWidth), window.innerWidth * 0.75)
    }
    const onMouseUp = () => {
      isResizingDrawer.value = false
      document.body.style.cursor = ''
      document.body.style.userSelect = ''
      localStorage.setItem('drawerWidth', String(Math.round(drawerWidth.value)))
      window.removeEventListener('mousemove', onMouseMove)
      window.removeEventListener('mouseup', onMouseUp)
    }
    window.addEventListener('mousemove', onMouseMove)
    window.addEventListener('mouseup', onMouseUp)
  }

  const showChanges = () => {
    eventBus.emit('splashShow')
  }

  watch(mdAndDown, () => {
    isDrawerOpen.value = false
  })
  watch(isDrawerOpen, () => {
    // Force close the drawer when it's not mobile
    if (isDrawerOpen.value && !mdAndDown.value) {
      isDrawerOpen.value = false
    }
    // A width persisted on a wider window may exceed the cap here
    if (isDrawerOpen.value) {
      drawerWidth.value = Math.min(drawerWidth.value, window.innerWidth * 0.75)
    }
  })

  const tabItems = [
    { title: 'Planner', icon: 'fas fa-ruler-triangle', href: '/' },
    { title: 'Graph (WIP)', icon: 'fas fa-project-diagram', href: '/graph' },
    { title: 'Parts & Recipes', icon: 'fas fa-hat-chef', href: '/parts' },
    { title: 'Change Log', icon: 'fas fa-scroll', href: '/changelog' },
  ]

  onMounted(async () => {
    // Wait a while for the page to load, then emit navigationReady event so the Planner can populate the drawer
    await new Promise(resolve => setTimeout(resolve, 1000))
    eventBus.emit('navigationReady')
  })
</script>

<style lang="scss" scoped>
// Kill the drawer's width transition while dragging so it tracks the cursor.
.v-navigation-drawer.resizing {
  transition: none;
}

// Same affordance as the docked sidebar's resize handle in Planner.vue.
// Absolutely positioned against the drawer root (the scrollable content
// wrapper is static), so it spans the full height and doesn't scroll away.
.drawer-resize-handle {
  position: absolute;
  top: 0;
  right: 0;
  width: 8px;
  height: 100%;
  cursor: col-resize;
  z-index: 10;
  border-right: 2px solid rgba(255, 255, 255, 0.12);

  &:hover, &.resizing {
    border-right-color: rgb(var(--v-theme-primary));
  }
}

.show-changes {
  color: inherit;
  cursor: pointer;
  text-decoration: underline;

  &:hover {
    opacity: 0.8;
  }
}
</style>
