import { readFileSync } from 'node:fs'
import neostandard from 'neostandard'
import pluginVue from 'eslint-plugin-vue'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'

// Globals for the components/composables auto-imported by unplugin-auto-import
// (regenerated into .eslintrc-auto-import.json by the vite plugin).
const autoImport = JSON.parse(readFileSync(new URL('./.eslintrc-auto-import.json', import.meta.url), 'utf-8'))

export default defineConfigWithVueTs(
  {
    ignores: [
      'node_modules/',
      'dist/',
      'public/',
      'coverage/',
      // Generated by the vite plugins (unplugin-auto-import / -vue-components / -vue-router)
      'src/auto-imports.d.ts',
      'src/components.d.ts',
      'src/typed-router.d.ts',
    ],
  },
  // Style layer: neostandard is the flat-config successor of eslint-config-standard,
  // which the old eslint-config-vuetify v1 extended. Must come before the Vue
  // configs so vue-eslint-parser wins on .vue files.
  ...neostandard(),
  pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  {
    languageOptions: {
      globals: {
        ...autoImport.globals,
      },
    },
  },
  {
    // Ported from eslint-config-vuetify v1 (which has no flat-config version at
    // this rule surface) plus this project's own overrides. Stylistic rules use
    // the @stylistic/ prefix neostandard registers.
    rules: {
      // The old @vue/eslint-config-typescript v13 setup tolerated these; keep
      // the baseline rather than flagging ~165 pre-existing usages.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',

      'no-var': 'error',
      complexity: ['error', 32],
      'no-console': 'off',
      'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
      'no-return-assign': 'off',
      'no-empty': 'error',
      'object-shorthand': ['error', 'always'],
      'prefer-const': ['error', {
        destructuring: 'all',
        ignoreReadBeforeAssign: true,
      }],
      'no-prototype-builtins': 'off',
      'no-void': 'off',
      'no-case-declarations': 'off',
      'sort-imports': ['warn', {
        ignoreDeclarationSort: true,
        ignoreCase: true,
      }],

      // allow paren-less arrow functions
      '@stylistic/arrow-parens': ['error', 'as-needed'],
      '@stylistic/quotes': ['error', 'single', {
        avoidEscape: true,
        allowTemplateLiterals: true,
      }],
      '@stylistic/comma-dangle': ['error', {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'only-multiline',
      }],
      '@stylistic/array-bracket-spacing': ['error', 'never'],
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/space-before-function-paren': ['error', {
        anonymous: 'always',
        named: 'always',
        asyncArrow: 'always',
      }],
      '@stylistic/no-extra-semi': 'error',
      '@stylistic/multiline-ternary': 'off',

      // Vue rules that apply outside .vue files too
      'vue/require-default-prop': 'off',
      'vue/require-prop-types': 'off',
      'vue/one-component-per-file': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/no-mutating-props': 'off',
      'vue/custom-event-name-casing': 'off', // No idea why this is a vue default as it breaks the event listeners!!
      'vue/attributes-order': ['error', {
        alphabetical: true,
      }],
    },
  },
  {
    files: ['**/*.vue'],
    rules: {
      '@stylistic/indent': 'off',
      'vue/script-indent': ['error', 2, {
        baseIndent: 1,
        switchCase: 1,
        ignores: [],
      }],
      'vue/html-closing-bracket-newline': ['error', {
        singleline: 'never',
        multiline: 'always',
      }],
      'vue/html-closing-bracket-spacing': 'error',
      'vue/max-attributes-per-line': ['error', {
        singleline: 4,
        multiline: 1,
      }],
      'vue/valid-v-on': 'off', // This rule doesn't allow empty event listeners
      'vue/no-v-html': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/valid-v-slot': ['error', { allowModifiers: true }],
    },
  },
)
